// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DAL.EF;

namespace WebApi.DAL.Migrations.InitialMaterials
{
    [DbContext(typeof(MaterialsDbContext))]
    partial class MaterialsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WebApi.DAL.Entities.Material", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("category")
                        .HasColumnType("int");

                    b.Property<string>("materialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("metaDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("metaFileSize")
                        .HasColumnType("float");

                    b.Property<string>("path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionNumber")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Materialss");
                });
#pragma warning restore 612, 618
        }
    }
}
